-- top3 avg temp filter by months in hbtn** database
-- command SELECT and GROUP ...
SELECT city,  AVG(value) AS avg_temp FROM temperatures WHERE month BETWEEN 7 AND 8 GROUP BY city ORDER BY avg_temp DESC LIMIT 3;
